project:
  type: website
  output-dir: docs

website:
  favicon: images/logo_ecotox.ico
  title: "Kits pédagogiques | YEG"
  navbar:
    left:
      - href: kits.qmd
        text: Nos jeux intelligents
      - href: ressources.qmd
        text: Besoin de plus d'informations ?
      - href: team.qmd
        text: Notre équipe
      - href: contact.qmd
        text: Nous contacter ?

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: false

editor: visual

